[package]
name = "rust-trial"
version = "0.1.0"
edition = "2021"
description = "Rust trial"
repository = "https://github.com/sekiyelab/rust-trial"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
