name: Job2

on:
  workflow_dispatch: {}
  schedule:
    # Runs at 00:00 UTC on Sundays
    - cron: '0 0 * * 0'

jobs:
  test:
    name: Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run job
        env:
          DEVELOPER_KEY0: ${{ secrets.DEVELOPER_KEY0 }}
          DEVELOPER_KEY1: ${{ secrets.DEVELOPER_KEY1 }}
          DEVELOPER_KEY2: ${{ secrets.DEVELOPER_KEY2 }}
          DEVELOPER_KEY3: ${{ secrets.DEVELOPER_KEY3 }}
          DEVELOPER_KEY4: ${{ secrets.DEVELOPER_KEY4 }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          QUERY_URL_BASE: ${{ secrets.QUERY_URL_BASE }}
          LOCATION_URL_BASE: ${{ secrets.LOCATION_URL_BASE }}
          LIVE_URL_BASE: ${{ secrets.LIVE_URL_BASE }}
          INFO_URL_BASE: ${{ secrets.INFO_URL_BASE }}
          DATA_URL: ${{ secrets.DATA_URL }}
          QUERIES_URL: ${{ secrets.QUERIES_URL }}
          BLACKLIST_URL: ${{ secrets.BLACKLIST_URL }}
          NON_LIVE_CAMERA_LIST_URL: ${{ secrets.NON_LIVE_CAMERA_LIST_URL }}
          WATCH_URL: ${{ secrets.WATCH_URL }}
        run: cargo run --bin=rust-trial --package=rust-trial --manifest-path=Cargo.toml --message-format=json
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
      - name: "Upload files"
        run: "gcloud storage cp geo.csv.gz blacklist.txt.gz non_live_camera.txt.gz gs://livecameramap-54d8d.appspot.com"
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -e --password="${{ secrets.ZIP_PASSWORD }}" geo.csv.gz.zip geo.csv.gz
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -e --password="${{ secrets.ZIP_PASSWORD }}" blacklist.txt.gz.zip blacklist.txt.gz
      - uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ./geo.csv.gz.zip
      - uses: actions/upload-artifact@v4
        with:
          name: artifact2
          path: ./blacklist.txt.gz.zip
